AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - activerecord-shard_for.gemspec
    - Guardfile
    - lib/activerecord/tasks/activerecord_shard_for.rake
    - gemfiles/**/*
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 128

Style/EmptyCaseCondition:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/ParallelAssignment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
