AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - activerecord-shard_for.gemspec
    - Guardfile
    - lib/activerecord/tasks/activerecord_shard_for.rake
    - gemfiles/**/*
    - vendor/bundle/**/*
  DisplayCopNames: true

Style/StderrPuts:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 128

Style/EmptyCaseCondition:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/FileName:
  Exclude:
    - Appraisals

Metrics/MethodLength:
  Max: 15

Style/ParallelAssignment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
