language: ruby
sudo: false
rvm:
  - 2.2.4
  - 2.3.1
before_install: gem install bundler -v 1.12.5
script: CODECLIMATE_REPO_TOKEN=dfc951e2d70b56ee62ffe989eb6286a6f21bf57209ccbd111bd336c372d8d06e bundle exec rspec
gemfile:
  - gemfiles/ar_4.1.0.gemfile
  - gemfiles/ar_4.1.7.gemfile
  - gemfiles/ar_4.1.8.gemfile
  - gemfiles/ar_4.2.gemfile
  - gemfiles/ar_5.0.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    # Rails 5 or later requires Ruby 2.2.0 or newer.
    - rvm: 2.1.9
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/ar_5.0.gemfile
