language: ruby
sudo: false
rvm:
- 2.3.8
- 2.4.10
- 2.5.8
- 2.6.6
- 2.7.1
branches:
  only:
    - master
before_install:
  - gem update --system 
  - gem update --remote bundler
cache: bundler
script:
- bundle exec rubocop
- bundle exec ruby spec/performance_test.rb
- bundle exec rspec
- CODECLIMATE_REPO_TOKEN=dfc951e2d70b56ee62ffe989eb6286a6f21bf57209ccbd111bd336c372d8d06e bundle exec codeclimate-test-reporter
gemfile:
- gemfiles/ar_5.0.gemfile
- gemfiles/ar_5.1.gemfile
- gemfiles/ar_5.2.gemfile
- gemfiles/ar_6.0.gemfile
- gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
  - gemfile: gemfiles/rails_edge.gemfile
  # rails6 and rails_edge required ruby version over 2.5.0
  exclude:
  - rvm: 2.3.8
    gemfile: gemfiles/rails_edge.gemfile
  - rvm: 2.4.10
    gemfile: gemfiles/rails_edge.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/ar_6.0.gemfile
  - rvm: 2.4.10
    gemfile: gemfiles/ar_6.0.gemfile
notifications:
  slack:
    secure: S1W/Lw+dH3wb8FfkMIWPZmr6M4Q6S2WMkSlanpKva1HM7K5QL7hXdmUl2yBUxJE26BHSsb1ScozMEzadyda2+i/W34UvZ7LXgKeHkUKEdjy/AmsSJPK1ZjMfgnv10tVgbEIusNb4bF/sSuChdZKK3ILwOlqIPDlQNdMwF1xRA2xt5J7tb26UgyIzoCI4P3bJYMULWsEkk+UwHiJH0YO9ulkTZI/j0N+hLXQLJTZPjmKtMk/tE0NbBmFVL4md89hUcR5gKTGGrNzEMJ58K+zqeDG/DubkcIbA5ZuqKv+oE5m0pDODZExxnC+oeENTvq/VfYwOfD0pTDrBNYjj+Bm3YiyGDzQAgov9XPDG8g/fKEs/LNAT79UZXkZlFO99Yn/vrYH9o5DKpOE9smENUXylb55MgLTUiYe17CTp7pB3trbJl3wwIbLjSmTjAdSUNgPv8qDP4uk3K4U32mknXCDDkU9EI7f6F731ocdoxsGarEBcPcgjs73Y84iwDteQp847Gigtgo4Y4TCWH657uzLolR2O8NSw+vWT0VNI9qtR5PZD7iVYtSp1qHtPAKowCztodewY2Nu+Ds9Z95udf4GPUkFg/SNEJPTPrQFLiiJZ8UYP8NJEuA+IP1tc2zG3zU/ADrjenRC1ZiupQG7OMH82y11408U6PcHFSlF+7NuDkac=
    on_success: change
    on_failure: always
